### ISSUE TITLE
Missing ipynb-File in Section 8

### ISSUE THREAD

**Issue by vfrauchiger** [PacktPublishing/Mastering-Big-Data-Analytics-with-PySpark#10]
Hi 

I have downloaded the current version of the github repo and I noticed that in Section 8 in the twitter_app folder the file twitter_app.ipynb is missing. 

I am working with your online course at packt publishing. 

Regards,

Vinz Frauchiger

**Comment by dannymeijer** [comment]
Dear Vinz,

Thank you for bringing this to my attention. Somehow the file was deleted
(it shouldn't have been).
I restored the file. If you pull from Git, it should be back inside the
twitter_app folder in Section 8.

Kind regards
Danny

**Comment by vfrauchiger** [comment]
Hi Danny

Thanks for the quick fix!

Have a great day!

Vinz
