### ISSUE TITLE
Running container inside a vm

### ISSUE THREAD

**Issue by alazarog7** [PacktPublishing/Mastering-Big-Data-Analytics-with-PySpark#12]
If you are running the container inside a vm, you should change line 290:
`port_map = {"{}/tcp".format(p): ("127.0.0.1", p) for p in self.ports}`
to
`port_map = {"{}/tcp".format(p): ("0.0.0.0", p) for p in self.ports}`
otherwise you cant connect from outside your vm

**Comment by dannymeijer** [comment]
I don't see why someone would want to run a docker from a VM tbh. But, feel free to submit a PR :)

**Comment by algbench** [comment]
> I don't see why someone would want to run a docker from a VM tbh. But, feel free to submit a PR :)

I was working on windows
