### ISSUE TITLE
No module named 'docker'

### ISSUE THREAD

**Issue by Rick0701** [PacktPublishing/Mastering-Big-Data-Analytics-with-PySpark#15]
Hello, 
when i try to run `python run_me.py` I get the following error:
ModuleNotFoundError: No module named 'docker'

Can you please help? 
Thank you
Riccardo

**Comment by dannymeijer** [comment]
Please verify the following for me:
- What python version are you running on?
- Did you install the requirements?

**Comment by Rick0701** [comment]
My python version is 3.9.7
Yes, I installed Docker and Visual Studio

**Comment by dannymeijer** [comment]
Can you give me the output of a ‘pip list’ command? Want to see if Docker
is mentioned in it.

**Comment by Rick0701** [comment]
This is the output of the `pip list `command: 

Package            Version
------------------ ---------
certifi            2021.5.30
charset-normalizer 2.0.4    
idna               3.2      
lxml               4.6.3    
numpy              1.21.1   
pandas             1.3.1
pandas-datareader  0.10.0
pip                21.2.3
python-dateutil    2.8.2
pytz               2021.1
requests           2.26.0
six                1.16.0
urllib3            1.26.6
WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Users\riccardo.ricci\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.

Thank you for your support

**Comment by Rick0701** [comment]
I was able to continue using `pip install docker`
