### ISSUE TITLE
'NoneType' object has no attribute 'id' 

### ISSUE THREAD

**Issue by jcodezy** [PacktPublishing/Mastering-Big-Data-Analytics-with-PySpark#6]
The run_my.py script seems to be running fine and almost finishes when I get this error.

`INFO     docker.api.build      58.14% | 26 Packages, 7 Downloading, 19 Extracted
INFO     docker.api.build      94.66% | 26 Packages, 7 Downloading, 19 Extracted
INFO     docker.api.build      94.66% | 26 Packages, 7 Downloading, 19 Extracted
INFO     docker.api.build     Image was built successfully
Traceback (most recent call last):
  File "run_me.py", line 324, in <module>
    course = Course()
  File "run_me.py", line 115, in __init__
    self._image()
  File "run_me.py", line 255, in _image
    self.build_image()
  File "run_me.py", line 244, in build_image
    logger.info("Image ID: %s", self.image.id)
AttributeError: 'NoneType' object has no attribute 'id'`

**Comment by dannymeijer** [comment]
What version of Python is this running on? Also, are the requirements installed?

Kind regards,
Danny Meijer
- Sent from my iPhone

**Comment by jcodezy** [comment]
version 3.7.7 and yes i've  used `pip install -r requirements.txt` for both requirements.txt files. I've managed to to bypass that logging error by commenting it out. The package download script has finished but now running into new issues and the script is not running a container and opening up the jupyter lab instance in my webbrowser:

Error: 
`requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/containers/c7ea97fc77de73dedfcb7131ac3ef50e6a7e4ba6e90799b000b071a203c43e07/start` 

While I have you here, when I run `docker image ls`, i have both the mastering-pyspark-ml and jupyter notebook images downloaded -- can you tell me how I can start up the proper instances without running the run_me.py script? Or are we expected to run the script every time we come back to the course?

**Comment by jcodezy** [comment]
okay, after many hours, i got it to work by removing all images, and doing it all manually. I think there are too many ways for things to go wrong with the script...also, the naming of docker images `mastering-pyspark-ml' and 'mastering_pyspark_ml' is confusing --just a friendly FYI. 

Thanks! you can mark as closed.
